//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UsersManagement.UsersApplicationService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserDataResponse", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class UserDataResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private UsersManagement.UsersApplicationService.User userField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string errorResponseField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public UsersManagement.UsersApplicationService.User user {
            get {
                return this.userField;
            }
            set {
                if ((object.ReferenceEquals(this.userField, value) != true)) {
                    this.userField = value;
                    this.RaisePropertyChanged("user");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string errorResponse {
            get {
                return this.errorResponseField;
            }
            set {
                if ((object.ReferenceEquals(this.errorResponseField, value) != true)) {
                    this.errorResponseField = value;
                    this.RaisePropertyChanged("errorResponse");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class User : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsernameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MyPasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Username {
            get {
                return this.UsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.UsernameField, value) != true)) {
                    this.UsernameField = value;
                    this.RaisePropertyChanged("Username");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string MyPassword {
            get {
                return this.MyPasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.MyPasswordField, value) != true)) {
                    this.MyPasswordField = value;
                    this.RaisePropertyChanged("MyPassword");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="UsersApplicationService.UsersServiceSoap")]
    public interface UsersServiceSoap {
        
        // CODEGEN: Generating message contract since element name GetUserByIdResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetUserById", ReplyAction="*")]
        UsersManagement.UsersApplicationService.GetUserByIdResponse GetUserById(UsersManagement.UsersApplicationService.GetUserByIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetUserById", ReplyAction="*")]
        System.Threading.Tasks.Task<UsersManagement.UsersApplicationService.GetUserByIdResponse> GetUserByIdAsync(UsersManagement.UsersApplicationService.GetUserByIdRequest request);
        
        // CODEGEN: Generating message contract since element name username from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UserAuthentication", ReplyAction="*")]
        UsersManagement.UsersApplicationService.UserAuthenticationResponse UserAuthentication(UsersManagement.UsersApplicationService.UserAuthenticationRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UserAuthentication", ReplyAction="*")]
        System.Threading.Tasks.Task<UsersManagement.UsersApplicationService.UserAuthenticationResponse> UserAuthenticationAsync(UsersManagement.UsersApplicationService.UserAuthenticationRequest request);
        
        // CODEGEN: Generating message contract since element name username from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UserRegistration", ReplyAction="*")]
        UsersManagement.UsersApplicationService.UserRegistrationResponse UserRegistration(UsersManagement.UsersApplicationService.UserRegistrationRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UserRegistration", ReplyAction="*")]
        System.Threading.Tasks.Task<UsersManagement.UsersApplicationService.UserRegistrationResponse> UserRegistrationAsync(UsersManagement.UsersApplicationService.UserRegistrationRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUserByIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUserById", Namespace="http://tempuri.org/", Order=0)]
        public UsersManagement.UsersApplicationService.GetUserByIdRequestBody Body;
        
        public GetUserByIdRequest() {
        }
        
        public GetUserByIdRequest(UsersManagement.UsersApplicationService.GetUserByIdRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetUserByIdRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int Id;
        
        public GetUserByIdRequestBody() {
        }
        
        public GetUserByIdRequestBody(int Id) {
            this.Id = Id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUserByIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUserByIdResponse", Namespace="http://tempuri.org/", Order=0)]
        public UsersManagement.UsersApplicationService.GetUserByIdResponseBody Body;
        
        public GetUserByIdResponse() {
        }
        
        public GetUserByIdResponse(UsersManagement.UsersApplicationService.GetUserByIdResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetUserByIdResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public UsersManagement.UsersApplicationService.UserDataResponse GetUserByIdResult;
        
        public GetUserByIdResponseBody() {
        }
        
        public GetUserByIdResponseBody(UsersManagement.UsersApplicationService.UserDataResponse GetUserByIdResult) {
            this.GetUserByIdResult = GetUserByIdResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UserAuthenticationRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UserAuthentication", Namespace="http://tempuri.org/", Order=0)]
        public UsersManagement.UsersApplicationService.UserAuthenticationRequestBody Body;
        
        public UserAuthenticationRequest() {
        }
        
        public UserAuthenticationRequest(UsersManagement.UsersApplicationService.UserAuthenticationRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UserAuthenticationRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        public UserAuthenticationRequestBody() {
        }
        
        public UserAuthenticationRequestBody(string username, string password) {
            this.username = username;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UserAuthenticationResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UserAuthenticationResponse", Namespace="http://tempuri.org/", Order=0)]
        public UsersManagement.UsersApplicationService.UserAuthenticationResponseBody Body;
        
        public UserAuthenticationResponse() {
        }
        
        public UserAuthenticationResponse(UsersManagement.UsersApplicationService.UserAuthenticationResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UserAuthenticationResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool UserAuthenticationResult;
        
        public UserAuthenticationResponseBody() {
        }
        
        public UserAuthenticationResponseBody(bool UserAuthenticationResult) {
            this.UserAuthenticationResult = UserAuthenticationResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UserRegistrationRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UserRegistration", Namespace="http://tempuri.org/", Order=0)]
        public UsersManagement.UsersApplicationService.UserRegistrationRequestBody Body;
        
        public UserRegistrationRequest() {
        }
        
        public UserRegistrationRequest(UsersManagement.UsersApplicationService.UserRegistrationRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UserRegistrationRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string firstName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string lastName;
        
        public UserRegistrationRequestBody() {
        }
        
        public UserRegistrationRequestBody(string username, string password, string firstName, string lastName) {
            this.username = username;
            this.password = password;
            this.firstName = firstName;
            this.lastName = lastName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UserRegistrationResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UserRegistrationResponse", Namespace="http://tempuri.org/", Order=0)]
        public UsersManagement.UsersApplicationService.UserRegistrationResponseBody Body;
        
        public UserRegistrationResponse() {
        }
        
        public UserRegistrationResponse(UsersManagement.UsersApplicationService.UserRegistrationResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UserRegistrationResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool UserRegistrationResult;
        
        public UserRegistrationResponseBody() {
        }
        
        public UserRegistrationResponseBody(bool UserRegistrationResult) {
            this.UserRegistrationResult = UserRegistrationResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface UsersServiceSoapChannel : UsersManagement.UsersApplicationService.UsersServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UsersServiceSoapClient : System.ServiceModel.ClientBase<UsersManagement.UsersApplicationService.UsersServiceSoap>, UsersManagement.UsersApplicationService.UsersServiceSoap {
        
        public UsersServiceSoapClient() {
        }
        
        public UsersServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UsersServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UsersServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UsersServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UsersManagement.UsersApplicationService.GetUserByIdResponse UsersManagement.UsersApplicationService.UsersServiceSoap.GetUserById(UsersManagement.UsersApplicationService.GetUserByIdRequest request) {
            return base.Channel.GetUserById(request);
        }
        
        public UsersManagement.UsersApplicationService.UserDataResponse GetUserById(int Id) {
            UsersManagement.UsersApplicationService.GetUserByIdRequest inValue = new UsersManagement.UsersApplicationService.GetUserByIdRequest();
            inValue.Body = new UsersManagement.UsersApplicationService.GetUserByIdRequestBody();
            inValue.Body.Id = Id;
            UsersManagement.UsersApplicationService.GetUserByIdResponse retVal = ((UsersManagement.UsersApplicationService.UsersServiceSoap)(this)).GetUserById(inValue);
            return retVal.Body.GetUserByIdResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<UsersManagement.UsersApplicationService.GetUserByIdResponse> UsersManagement.UsersApplicationService.UsersServiceSoap.GetUserByIdAsync(UsersManagement.UsersApplicationService.GetUserByIdRequest request) {
            return base.Channel.GetUserByIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<UsersManagement.UsersApplicationService.GetUserByIdResponse> GetUserByIdAsync(int Id) {
            UsersManagement.UsersApplicationService.GetUserByIdRequest inValue = new UsersManagement.UsersApplicationService.GetUserByIdRequest();
            inValue.Body = new UsersManagement.UsersApplicationService.GetUserByIdRequestBody();
            inValue.Body.Id = Id;
            return ((UsersManagement.UsersApplicationService.UsersServiceSoap)(this)).GetUserByIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UsersManagement.UsersApplicationService.UserAuthenticationResponse UsersManagement.UsersApplicationService.UsersServiceSoap.UserAuthentication(UsersManagement.UsersApplicationService.UserAuthenticationRequest request) {
            return base.Channel.UserAuthentication(request);
        }
        
        public bool UserAuthentication(string username, string password) {
            UsersManagement.UsersApplicationService.UserAuthenticationRequest inValue = new UsersManagement.UsersApplicationService.UserAuthenticationRequest();
            inValue.Body = new UsersManagement.UsersApplicationService.UserAuthenticationRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            UsersManagement.UsersApplicationService.UserAuthenticationResponse retVal = ((UsersManagement.UsersApplicationService.UsersServiceSoap)(this)).UserAuthentication(inValue);
            return retVal.Body.UserAuthenticationResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<UsersManagement.UsersApplicationService.UserAuthenticationResponse> UsersManagement.UsersApplicationService.UsersServiceSoap.UserAuthenticationAsync(UsersManagement.UsersApplicationService.UserAuthenticationRequest request) {
            return base.Channel.UserAuthenticationAsync(request);
        }
        
        public System.Threading.Tasks.Task<UsersManagement.UsersApplicationService.UserAuthenticationResponse> UserAuthenticationAsync(string username, string password) {
            UsersManagement.UsersApplicationService.UserAuthenticationRequest inValue = new UsersManagement.UsersApplicationService.UserAuthenticationRequest();
            inValue.Body = new UsersManagement.UsersApplicationService.UserAuthenticationRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            return ((UsersManagement.UsersApplicationService.UsersServiceSoap)(this)).UserAuthenticationAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UsersManagement.UsersApplicationService.UserRegistrationResponse UsersManagement.UsersApplicationService.UsersServiceSoap.UserRegistration(UsersManagement.UsersApplicationService.UserRegistrationRequest request) {
            return base.Channel.UserRegistration(request);
        }
        
        public bool UserRegistration(string username, string password, string firstName, string lastName) {
            UsersManagement.UsersApplicationService.UserRegistrationRequest inValue = new UsersManagement.UsersApplicationService.UserRegistrationRequest();
            inValue.Body = new UsersManagement.UsersApplicationService.UserRegistrationRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.firstName = firstName;
            inValue.Body.lastName = lastName;
            UsersManagement.UsersApplicationService.UserRegistrationResponse retVal = ((UsersManagement.UsersApplicationService.UsersServiceSoap)(this)).UserRegistration(inValue);
            return retVal.Body.UserRegistrationResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<UsersManagement.UsersApplicationService.UserRegistrationResponse> UsersManagement.UsersApplicationService.UsersServiceSoap.UserRegistrationAsync(UsersManagement.UsersApplicationService.UserRegistrationRequest request) {
            return base.Channel.UserRegistrationAsync(request);
        }
        
        public System.Threading.Tasks.Task<UsersManagement.UsersApplicationService.UserRegistrationResponse> UserRegistrationAsync(string username, string password, string firstName, string lastName) {
            UsersManagement.UsersApplicationService.UserRegistrationRequest inValue = new UsersManagement.UsersApplicationService.UserRegistrationRequest();
            inValue.Body = new UsersManagement.UsersApplicationService.UserRegistrationRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.firstName = firstName;
            inValue.Body.lastName = lastName;
            return ((UsersManagement.UsersApplicationService.UsersServiceSoap)(this)).UserRegistrationAsync(inValue);
        }
    }
}
